// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSnCdU6_NowkkjP1VPZGdezNePDOM6eSc',
    appId: '1:361376502244:web:d0d5e8f2f1aeed996237f1',
    messagingSenderId: '361376502244',
    projectId: 'pomodoro-tasks-nt-2026',
    authDomain: 'pomodoro-tasks-nt-2026.firebaseapp.com',
    storageBucket: 'pomodoro-tasks-nt-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiV3xZ-Xk2aeo_SGDzsSy_KOq-YUA55VI',
    appId: '1:361376502244:android:c7c700d425f0263a6237f1',
    messagingSenderId: '361376502244',
    projectId: 'pomodoro-tasks-nt-2026',
    storageBucket: 'pomodoro-tasks-nt-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVHIZs62HJ94xxOKU9XEjS4pgMLCb7Y5U',
    appId: '1:361376502244:ios:84983b34053f78696237f1',
    messagingSenderId: '361376502244',
    projectId: 'pomodoro-tasks-nt-2026',
    storageBucket: 'pomodoro-tasks-nt-2026.firebasestorage.app',
    iosBundleId: 'com.pomodoro.pomodoroTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVHIZs62HJ94xxOKU9XEjS4pgMLCb7Y5U',
    appId: '1:361376502244:ios:84983b34053f78696237f1',
    messagingSenderId: '361376502244',
    projectId: 'pomodoro-tasks-nt-2026',
    storageBucket: 'pomodoro-tasks-nt-2026.firebasestorage.app',
    iosBundleId: 'com.pomodoro.pomodoroTasks',
  );
}
