name: iOS-ipa-build

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

env:
  RELEASE_VERSION: 1.0.${{ github.run_number }}

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter clean
      - run: rm -f ios/Podfile.lock
      - run: rm -rf ios/Pods
      - run: flutter pub get

      - run: pod install --repo-update
        working-directory: ios

      - run: flutter build ios --release --no-codesign --build-name "$RELEASE_VERSION" --build-number "${{ github.run_number }}"

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 PomodoroTasks-${RELEASE_VERSION}.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/PomodoroTasks-${{ env.RELEASE_VERSION }}.ipa
          asset_name: PomodoroTasks-${{ env.RELEASE_VERSION }}.ipa
          tag: v${{ env.RELEASE_VERSION }}
          release_name: Pomodoro Tasks v${{ env.RELEASE_VERSION }}
          overwrite: false
          body: "Automated iOS IPA build for v${{ env.RELEASE_VERSION }}."
